"""Generate a compact Markdown ALM report."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from yield_curve_alm_engine.config import OUTPUTS
from yield_curve_alm_engine.curve.base_curve import ZeroCurve
from yield_curve_alm_engine.curve.shocks import get_stress_scenarios
from yield_curve_alm_engine.instruments.bonds import Bond
from yield_curve_alm_engine.risk.curve_analytics import compute_curve_analytics
from yield_curve_alm_engine.risk.surplus import (
    parallel_surplus_shock_comparison,
    run_surplus_scenarios,
)
from yield_curve_alm_engine.scripts.build_alm_dashboard import build_dashboard_tables
from yield_curve_alm_engine.scripts.common import (
    add_input_arguments,
    load_bonds,
    load_curve,
    load_liabilities,
)


def _format_number(value: float) -> str:
    if abs(value) >= 1_000:
        return f"{value:,.0f}"
    return f"{value:,.6f}".rstrip("0").rstrip(".")


def _markdown_table(frame: pd.DataFrame, columns: list[str] | None = None) -> str:
    table = frame.loc[:, columns].copy() if columns else frame.copy()
    header = "| " + " | ".join(table.columns) + " |"
    separator = "| " + " | ".join("---" for _ in table.columns) + " |"
    rows = []
    for row in table.itertuples(index=False):
        values = [
            _format_number(value) if isinstance(value, float) else str(value)
            for value in row
        ]
        rows.append("| " + " | ".join(values) + " |")
    return "\n".join([header, separator, *rows])


def build_report_tables(
    curve: ZeroCurve,
    bonds: list[Bond],
    liabilities: pd.DataFrame,
) -> dict[str, pd.DataFrame]:
    """Build the tables used by the Markdown report."""
    dashboard_tables = build_dashboard_tables(curve, bonds, liabilities)
    stress_results = run_surplus_scenarios(
        bonds=bonds,
        liabilities=liabilities,
        base_curve=curve,
        scenarios=get_stress_scenarios(),
        include_base=True,
    )
    shock_comparison = pd.DataFrame(
        [parallel_surplus_shock_comparison(bonds, liabilities, curve, shock_size=0.0001)]
    )

    return {
        "summary": dashboard_tables["summary"],
        "curve_analytics": compute_curve_analytics(curve),
        "key_rate_report": dashboard_tables["key_rate_report"],
        "cashflow_gap_report": dashboard_tables["cashflow_gap_report"],
        "stress_results": stress_results,
        "shock_comparison": shock_comparison,
    }


def _summary_metric(summary: pd.DataFrame, metric: str) -> float:
    return float(summary.loc[summary["metric"] == metric, "value"].iloc[0])


def build_report_markdown(
    tables: dict[str, pd.DataFrame],
    input_note: str,
) -> str:
    """Build a concise Markdown report from precomputed ALM tables."""
    summary = tables["summary"]
    curve_analytics = tables["curve_analytics"]
    stress_results = tables["stress_results"]
    shock_comparison = tables["shock_comparison"]

    summary_rows = summary[
        summary["metric"].isin(
            [
                "asset_market_value",
                "liability_present_value",
                "surplus",
                "asset_modified_duration",
                "liability_modified_duration",
                "duration_gap",
                "estimated_surplus_change_1bp_up",
            ]
        )
    ]

    curve_rows = curve_analytics[
        curve_analytics["metric"].isin(
            [
                "zero_rate_1y",
                "zero_rate_10y",
                "zero_rate_30y",
                "slope_2y_10y",
                "curvature_2y_5y_10y",
            ]
        )
    ]

    stress_rows = stress_results.loc[
        :,
        ["scenario", "asset_value", "liability_value", "surplus", "surplus_change"],
    ]
    shock_rows = shock_comparison.loc[
        :,
        [
            "parallel_shock_bps",
            "exact_surplus_change",
            "estimated_surplus_change",
            "estimate_error",
        ],
    ]

    return "\n".join(
        [
            "# ALM Research Report",
            "",
            "This report is generated by a stylized ALM and fixed-income risk laboratory.",
            "It is intended for transparent portfolio/research analytics, not production reporting.",
            "",
            "## Input Scope",
            "",
            input_note,
            "",
            "## Base-Case Snapshot",
            "",
            _markdown_table(summary_rows, ["metric", "value", "unit"]),
            "",
            "## Curve Diagnostics",
            "",
            _markdown_table(curve_rows, ["metric", "value", "unit"]),
            "",
            "## Surplus Shock Diagnostic",
            "",
            "The table compares exact revaluation with a first-order duration estimate for a +1 bp parallel rate shock.",
            "",
            _markdown_table(shock_rows),
            "",
            "## Stress-Test Summary",
            "",
            _markdown_table(stress_rows),
            "",
            "## Interpretation",
            "",
            f"- Base surplus: {_format_number(_summary_metric(summary, 'surplus'))}.",
            f"- Duration gap: {_format_number(_summary_metric(summary, 'duration_gap'))} years.",
            "- Key-rate and cash-flow matching CSVs provide the more granular ALM diagnostics.",
            "",
            "## Limitations",
            "",
            "- The model uses stylized fixed-rate bullet assets and simplified liability cash flows.",
            "- ECB curves, when used, are public spot-rate inputs normalized into local CSV files.",
            "- The workflow is not a regulatory valuation system, a trading system or a market data management stack.",
            "",
            "## Related Outputs",
            "",
            "- `outputs/alm_dashboard_summary.csv`",
            "- `outputs/key_rate_report.csv`",
            "- `outputs/cashflow_gap_report.csv`",
            "- `outputs/stress_test_results.csv`",
            "- `outputs/curve_scenarios.png`",
            "- `outputs/surplus_by_scenario.png`",
            "- `outputs/key_rate_pv01.png`",
            "- `outputs/cashflow_gap.png`",
            "",
        ]
    )


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a compact Markdown ALM report.")
    add_input_arguments(parser)
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUTS / "alm_report.md",
        help="Markdown output path. Defaults to outputs/alm_report.md.",
    )
    return parser.parse_args(argv)


def _input_note(args: argparse.Namespace) -> str:
    if args.curve_csv or args.bonds_csv or args.liabilities_csv:
        return (
            "The report uses local CSV inputs where supplied. The valuation step "
            "runs offline from those files; live internet is only used by the "
            "separate ECB fetch command when refreshing curve CSVs."
        )
    return (
        "The report uses the built-in synthetic curve, bond portfolio and "
        "liability schedule provided for reproducible examples."
    )


def main() -> None:
    args = parse_args()
    curve = load_curve(args.curve_csv)
    bonds = load_bonds(args.bonds_csv)
    liabilities = load_liabilities(args.liabilities_csv)

    tables = build_report_tables(curve, bonds, liabilities)
    markdown = build_report_markdown(tables, input_note=_input_note(args))

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown)

    tables["curve_analytics"].to_csv(OUTPUTS / "report_curve_analytics.csv", index=False)
    tables["shock_comparison"].to_csv(OUTPUTS / "report_shock_comparison.csv", index=False)

    print(f"Markdown ALM report saved to: {output_path}")
    print(f"Supporting report tables saved to: {OUTPUTS}")


if __name__ == "__main__":
    main()
